# Generated by Django 4.0.6 on 2023-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_origin', models.CharField(choices=[('Keratinocytes', 'Keratinocytes'), ('Fibroblasts', 'Fibroblasts'), ('Melanocytes', 'Melanocytes'), ('Langerhans cells', 'Langerhans cells')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('vat_number', models.CharField(max_length=255)),
                ('civility', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('skin_models', models.ManyToManyField(to='main.skinmodel')),
            ],
        ),
    ]
