# Generated by Django 4.0.6 on 2023-04-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='skin_models',
        ),
        migrations.AddField(
            model_name='skinmodel',
            name='quote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='skin_models', to='main.quote'),
            preserve_default=False,
        ),
    ]
