# Generated by Django 4.0.6 on 2023-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_quote_skin_models_skinmodel_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='cell_origin',
            field=models.CharField(choices=[('Keratinocytes', 'Keratinocytes'), ('Fibroblasts', 'Fibroblasts'), ('Melanocytes', 'Melanocytes'), ('Langerhans cells', 'Langerhans cells')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SkinModel',
        ),
    ]
